### ISSUE TITLE
TR extension recorded wrong elements

### ISSUE THREAD

**Issue by prabhakarbattula** [bigbinary/trinity-radar-chromext#24]
@rkr090 _A

TR extension recorded wrong elements
https://app.trinityradar.com/projects/maxwell_pb/categories/864/test_cases/4186?editor=true&step=75445&referrer=https://app.trinityradar.com/projects/maxwell_pb/categories/864/test_cases/4186/test_results/206708

![image](https://user-images.githubusercontent.com/5687294/28837057-084320ee-7709-11e7-8ecb-76aae8398229.png)

![image](https://user-images.githubusercontent.com/5687294/28837137-557e8fce-7709-11e7-97fa-efb1f5324224.png)

**Comment by rkr090** [comment]
@rkr090 _a

I have fixed the selectors manually, I will discuss this in tomorrows standup.

**Comment by rkr090** [comment]
Closing in favor of #26
